### ISSUE TITLE
Regression in 1.82 command palette is broken

### ISSUE THREAD

**Issue by kevinvalk** [CodinGame/monaco-vscode-api#199]
When you currently visit https://codingame.github.io/monaco-vscode-api/  and open the command palette and remove the ">" character it will throw the error as shown below. This in turn breaks quick file open functionality (registered in `registerFileSearchProvider`) which does not work anymore in this demo (nor in my own code).

**I think it is related, but any commands registered in `contributes.commands` via extension manifest also do not show up in the command palette anymore. Even if you have set keybindings, they will also not work.**

```error
index-9c7a3a1c.js:3 Uncaught Error: [createInstance] r_ depends on UNKNOWN service quickChatService.

Error: [createInstance] r_ depends on UNKNOWN service quickChatService.
    at J3._throwIfStrict (index-9c7a3a1c.js:714:4572)
    at J3._createInstance (index-9c7a3a1c.js:714:1121)
    at J3.createInstance (index-9c7a3a1c.js:714:914)
    at hwe.getOrInstantiateProvider (index-9c7a3a1c.js:702:6752)
    at kq.value (index-9c7a3a1c.js:702:6392)
    at D._deliver (index-9c7a3a1c.js:8:2987)
    at D._deliverQueue (index-9c7a3a1c.js:8:3078)
    at D.fire (index-9c7a3a1c.js:8:3504)
    at GD.doSetValue (index-9c7a3a1c.js:702:41619)
    at kq.value (index-9c7a3a1c.js:702:44454)
    at index-9c7a3a1c.js:3:12
(anonymous) @ index-9c7a3a1c.js:3
setTimeout (async)
Xft.unexpectedErrorHandler @ index-9c7a3a1c.js:1
onUnexpectedError @ index-9c7a3a1c.js:5
St @ index-9c7a3a1c.js:5
_deliver @ index-9c7a3a1c.js:8
_deliverQueue @ index-9c7a3a1c.js:8
fire @ index-9c7a3a1c.js:8
doSetValue @ index-9c7a3a1c.js:702
(anonymous) @ index-9c7a3a1c.js:702
_deliver @ index-9c7a3a1c.js:8
fire @ index-9c7a3a1c.js:8
onValueChange @ index-9c7a3a1c.js:214
(anonymous) @ index-9c7a3a1c.js:214

```

**Comment by CGNonofr** [comment]
Thanks for the report! well spotted

**Comment by CGNonofr** [comment]
For it to be displayed, I think it should be added in the `menus.commandPalette` section

**Comment by kevinvalk** [comment]
Mmm, when I used [v1.81.7](https://github.com/CodinGame/monaco-vscode-api/releases/tag/v1.81.7) monaco-vscode-api commands would show up without using the `menus.commandPalette` settings. If I read https://code.visualstudio.com/api/references/contribution-points#contributes.commands it also makes sense it does:
> By default, commands show in the Command Palette (⇧⌘P) but they can also show in other [menus](https://code.visualstudio.com/api/references/contribution-points#contributes.menus).

Smallest example that I could come up with  (running 1.82.4-next.1) that shows that commands are not properly registered in any menu when using registerExtension. Maybe I am still doing something wrong?

```typescript
  await initializeMonacoService({
    ...getConfigurationServiceOverride(monaco.Uri.from({ scheme: 'file', path: '' })), // Required to have command palette work.
    ...getKeybindingsServiceOverride({
      shouldUseGlobalKeybindings: () => true,
    })
    ...getQuickAccessServiceOverride({
      isKeybindingConfigurationVisible: () => false,
      shouldUseGlobalPicker: () => true,
    }),
  }).then(async () => {
    await initializeVscodeExtensions(); // I think this call is not needed.

    // It does not really matter "where" I place this call as in, if VSCode is initialized or not.
    const { getApi } = registerExtension(
      {
        name: 'test-command',
        publisher: 'some-publisher',
        version: '1.0.0',
        engines: {
          vscode: '*',
        },
        contributes: {
          menus: {
            commandPalette: [
              {
                command: 'some-command',
              },
            ],
            'editor/context': [
              {
                command: 'some-command',
              },
            ],
          },
          commands: [
            {
              command: 'some-command',
              title: 'Some special command',
            },
          ],
        },
      },
      // @ts-expect-error const enum problems verbatimModuleSyntax https://github.com/microsoft/TypeScript/issues/52669, https://github.com/microsoft/TypeScript/issues/16671
      ExtensionHostKind.LocalProcess,
      {}
    );
    (await getApi()).commands.registerCommand('some-command', () => {
      console.log('I am registered and can be called, just not from a menu!');
    });

    await vscode.commands.executeCommand('some-command');

    MenuRegistry.addCommand({
      id: 'some-command',
      title: 'Manually registered some special command does show up',
    });

```

**Comment by CGNonofr** [comment]
I'm unable to reproduce

If I add
```
registerExtension(
  {
    name: 'test-command',
    publisher: 'some-publisher',
    version: '1.0.0',
    engines: {
      vscode: '*'
    },
    contributes: {
      commands: [
        {
          command: 'some-command',
          title: 'Some special command'
        }
      ]
    }
  },
  ExtensionHostKind.LocalProcess,
  {}
)
```
in the demo, the `Some special command` command appears in the palette

![image](https://github.com/CodinGame/monaco-vscode-api/assets/23257479/92aac92c-80c3-4ae7-88f7-be93fc2d0785)

Didn't I understand correctly?

**Comment by kevinvalk** [comment]
Thanks a lot for testing!!! Then it has to be something that I am doing.

Then this can be closed when #200 is merged 🎉

**Comment by CGNonofr** [comment]
Maybe it's worth investigating, there is maybe a race condition or a specific usage that doesn't work

We already had some issue related to extension added just after the bootstrap, because that's a use-case vscode doesn't have

**Comment by kevinvalk** [comment]
Found it! _For future prosperity, or maybe you can add some notes to the docs on registerExtension?_

This is probably user error... I think I still do not understand exactly what `extensions/initialize()` call is used for. But extensions fail to register (silently) if you register them in the promise or some time after a call to `extensions/initialize()`.

```typescript
import { ExtensionHostKind, initialize, registerExtension } from 'vscode/extensions';
initialize().then(async () => {
    registerExtension(
      {
        name: 'test-command5',
        publisher: 'some-publisher',
        version: '1.0.0',
        engines: {
          vscode: '*',
        },
        contributes: {
          commands: [
            {
              command: 'some-command5',
              title: 'Extension after extensions/initialize promise',
              category: 'Special',
            },
          ],
        },
      },
      // @ts-expect-error because verbatim sucks
      ExtensionHostKind.LocalProcess,
      {}
    );
});

**I continued testing a bit more and it seems there is a some window (around 1 second) after the `extensions/initialize()` in which you CANNOT call `registerExtension` (as in, it will silently drop).**
